name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  ci:
    uses: Amulet-Laboratories/.github/.github/workflows/ci.yml@main
    with:
      type: monorepo
    secrets: inherit
