name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  ci:
    uses: Amulet-Laboratories/.github/.github/workflows/ci.yml@77c5bbe581db1d17410e537217654614ef4cb66a # main
    with:
      node-version: '22'
    secrets:
      PKG_READ_TOKEN: ${{ secrets.PKG_READ_TOKEN }}
